### ISSUE TITLE
fix auth deprecation warning from octokit

### ISSUE THREAD

**Issue by outofambit** [desktop/dugite-native#229]
```shellsession
$ npm run generate-release-notes

> dugite-native@ generate-release-notes /Users/outofambit/src/dugite-native
> node script/generate-release-notes.js

{ Deprecation: [@octokit/rest] octokit.authenticate() is deprecated. Use "auth" constructor option instead.
    at authenticate (/Users/outofambit/src/dugite-native/node_modules/@octokit/rest/plugins/authentication-deprecated/authenticate.js:9:44)
    at run (/Users/outofambit/src/dugite-native/script/generate-release-notes.js:56:11)
    at Object.<anonymous> (/Users/outofambit/src/dugite-native/script/generate-release-notes.js:215:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3) name: 'Deprecation' }
```

**Comment by shiftkey** [comment]
#214 has some other examples of what changes to Octokit need to be made
