### ISSUE TITLE
linux error

### ISSUE THREAD

**Issue by gengjiawen** [desktop/dugite-native#46]
I build a linux distro for desktop, but user report save options is not working, I look into the stacktrace, and find maybe related to this.
Related Issue: https://github.com/gengjiawen/desktop/issues/1

Stacktrace:
```
Uncaught (in promise) Error: spawn ENOTDIR
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at Object.exports.execFile (child_process.js:160:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:219:18)
    at /media/sf_Developer/webpack:/app/~/dugite/build/lib/git-process.js:45:1
    at Function.exec (/media/sf_Developer/webpack:/app/~/dugite/build/lib/git-process.js:28:1)
    at Q.measure (/media/sf_Developer/webpack:/app/src/lib/git/core.ts:110:30)
    at Object.<anonymous> (/media/sf_Developer/webpack:/app/src/ui/lib/git-perf.ts:19:10)
    at Generator.next (<anonymous>
```

**Comment by shiftkey** [comment]
`ENOTDIR` is an error raised by Node which suggests that the directory path to wherever `dugite` is trying to launch it's version of Git doesn't exist. 

Please open an issue over on https://github.com/desktop/dugite with more information about recreating the issue. This repository is for the compiling and packaging of Git itself, not the bindings to languages like Node/Electron.
